#!/bin/bash

function getTodoFile {
    local filename

    # see if FILE has already been set (eg, via command line arguments),
    # if not, try and grab it from ENV variable
    if [ -z "$FILE" ]; then
        filename=$TODO_FILE
    fi

    # if we still don't have FILE set, default to $HOME/todo.txt
    if [ -z "$FILE" ]; then
        filename=$HOME/todo.txt
    fi
    echo "$filename"
}

function listTodo {
    # sort the file, and filter out completed items (ie, starting with x)
    sort $1 | grep -v '^x'
}

function addTodo {

    local priority
    local message
    local projects
    local contexts

    # priority
    while true; do
        read -p 'Priority (Optional) [A-Z]: ' priority

        # convert to upper case
        priority=${priority^^}

        # validate priority, break if it's ok
        if [[ $priority =~ ^[A-Z]?$ ]]; then
            if [ "$priority" ]; then
                local styledPriority="($priority) "
            fi
            break
        fi
    done

    # message
    while true; do
        read -p 'Message: ' message

        # validate there is some message
        if [[ $message =~ .*[^\s]+.* ]]; then
            break
        fi
    done

    # projects
    while true; do
        read -p 'Projects (Optional, space delimited): ' projects
        local styledProjects

        # validate projects, break if it's ok
        if [[ $projects =~ ^[a-zA-Z0-9\ ]*$ ]]; then

            # prepend "+" to each project
            for word in ${projects}; do
                styledProjects+=" +$word"
            done

            break
        fi
    done

    # contexts
    while true; do
        read -p 'Contexts (Optional, space delimited): ' contexts
        local styledContexts

        # validate contexts, break if it's ok
        if [[ $contexts =~ ^[a-zA-Z0-9\ ]*$ ]]; then

            # prepend "@" to each context
            for word in ${contexts}; do
                styledContexts+=" @$word"
            done

            break
        fi
    done

    local todoLine="$styledPriority$message$styledProjects$styledContexts"
    echo "$todoLine" >> "$1"
    echo "$todoLine"
}

#TODO parse parameters

filename=$(getTodoFile)
echo "file is $filename"
#listTodo $filename
addTodo $filename
