#!/bin/bash

function getTodoFile {
    local filename

    # see if FILE has already been set (eg, via command line arguments),
    # if not, try and grab it from ENV variable
    if [ -z "$FILE" ]; then
        filename=$TODO_FILE
    fi

    # if we still don't have FILE set, default to $HOME/todo.txt
    if [ -z "$FILE" ]; then
        filename=$HOME/todo.txt
    fi
    echo "$filename"
}

function listTodo {
    # sort the file, and filter out completed items (ie, starting with x)
    sort $1 | grep -v '^x'
}

function addTodo {

    local priority
    local message
    local projects
    local context

    while true; do
        read -p 'Priority [A-Z ]: ' priority
        # validate priority, break if it's ok
        if [[ $priority =~ ^[A-Z]?$ ]]; then
            break
        fi
    done

    echo "priority is $priority"
}

filename=$(getTodoFile)
echo "file is $filename"
#listTodo $filename
addTodo
